## 00 Broadcast in numpy
### Description
Given a one-dimensional array of length '`n`', complete the '`add_in_broadcast_way`' function to return a '`n*n`' matrix (row i, column j of this matrix equals to the addition of the i-th element and j-th element of the given array).
### Input
The input of the '`add_in_broadcast_way`' function is a vector of length '`n`'.
### Output
The output of the '`add_in_broadcast_way`' function is a '`n*n`' matrix.

**Sample Input 1** `1 0 8 1 0 3 9 1`

**Sample Output 1**
```
2  1  9  2  1  4 10  2
1  0  8  1  0  3  9  1
9  8 16  9  8 11 17  9
2  1  9  2  1  4 10  2
1  0  8  1  0  3  9  1
4  3 11  4  3  6 12  4
10  9 17 10  9 12 18 10
2  1  9  2  1  4 10  2
```
### Hint
Broadcast is a way of Numpy to calculate the array of different shapes. The arithmetic operation of array is usually carried out on the corresponding elements.

Broadcast principle: two arrays are considered broadcast compatible if the length of the axis of the trailing dimension (i.e., the dimension from the end) is the same, or the length of one of them is 1. The broadcast will take place on the missing and / or length 1 dimension.

One example is:
```
a = [1 2 3 4 5]
a + 5 = [6 7 8 9 10]
```
, where5is broadcasted to`[5 5 5 5 5]`, then element-wise addition,`[1 2 3 4 5]` + `[6 7 8 9 10]`, is executed.

Another example is:
```
a = [1 2 3 4 5]
b = 
[[11]
 [12]
 [13]
 [14]
 [15]]
a + b = 
[[12 13 14 15 16]
 [13 14 15 16 17]
 [14 15 16 17 18]
 [15 16 17 18 19]
 [16 17 18 19 20]]
```
, where a is broadcasted to
```
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
```
, b is broadcasted to
```
[[11 11 11 11 11]
 [12 12 12 12 12]
 [13 13 13 13 13]
 [14 14 14 14 14]
 [15 15 15 15 15]]
```
, then element-wise addition is executed.

'To address this problem, you should transpose the reshaped `a_vector`, first'.

Documents about how to transpose a numpy array: '[numpy.transpose](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html)' or '[numpy.ndarray.T](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.T.html)'.

Documents of other meaningful methods of numpy can be found at '[Quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html)' and '[Absolute Beginners Tutorial](https://numpy.org/doc/stable/user/absolute_beginners.html)'

In [1]:
import numpy as np
def add_in_broadcast_way(a_vector):
    a_vector = a_vector.reshape((1, -1))
    # a_vector is plussed to the transpose of itself
    a1 = a_vector.T
    a = a1 + a_vector
    return a

# You should only complete the above function

def input_a_vector():
    arow = [int(ele) for ele in input().split()]
    a_vector = np.array(arow)
    return a_vector
    
input_data = input_a_vector()
output = add_in_broadcast_way(input_data)


for row in output:
    print(*row.tolist(), sep=' ')

print()

1 0 8 1 0 3 9 1
2 1 9 2 1 4 10 2
1 0 8 1 0 3 9 1
9 8 16 9 8 11 17 9
2 1 9 2 1 4 10 2
1 0 8 1 0 3 9 1
4 3 11 4 3 6 12 4
10 9 17 10 9 12 18 10
2 1 9 2 1 4 10 2



## 01 Finding zero elements in an integer matrix
### Description
Given an integer matrix, you should 'complete the `finding_zero_elements` function' to return all the coordinates of zero elements in the given matrix as a two dimension matrix where each row is one coordinate.
### Input
The input of the '`finding_zero_elements`' function is a matrix.
### Output
The output of the'`finding_zero_elements`' function is a two dimension matrix where each row is one coordinate of the zero element.

**Sample Input 1**
```
0 7 14 0
8 2 0 2
3 0 0 9
```
**Sample Output 1**
```
0 0
0 3
1 2
2 1
2 2
```
### Hint
You should complete this task with the method of '[numpy.argwhere](https://numpy.org/doc/stable/reference/generated/numpy.argwhere.html)'.

Supplementary Reference:
- Documents of other meaningful methods of numpy can be found at '[Quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html)' and '[Absolute Beginners Tutorial](https://numpy.org/doc/stable/user/absolute_beginners.html)'

In [2]:
def finding_zero_elements(a_matrix):
    # a function to return all the coordinates of zero elements in the given matrix as a two dimension array
    a = np.argwhere(a_matrix == 0)
    return a

# you should only complete the above function

def input_a_matrix():
    # nrow = [int(ele) for ele in input().split()][0]
    row_list = []
    while True:
        arow = [int(ele) for ele in input().split()]
        if len(arow) == 0:
            break
        row_list.append(arow)
    
    a_matrix = np.array(row_list)
    return a_matrix

a_matrix = input_a_matrix()
output = finding_zero_elements(a_matrix)

for row in output:
    print(*row.tolist(), sep=' ')

print()

0 7 14 0
8 2 0 2
3 0 0 9

0 0
0 3
1 2
2 1
2 2



## 02 Singular Value Decomposition
### Description
![A5_01.svg](https://upload.wikimedia.org/wikipedia/commons/c/c8/Singular_value_decomposition_visualisation.svg)
### Input
The input of the '`singular_value_decomposition`' function is a '`m*n`' matrix.
### Output
The output of the '`singular_value_decomposition`' function is the matrix '`S`' which is original singular matrix.

**Sample Input 1**
```
219 47 68
51 17 120
102 94 160
49 171 190
203 46 205
```
**Sample Output 1** `479.714 181.986 82.291`
### Hint
Reference:
- [Singular value decomposition - Wikipedia](https://en.wikipedia.org/wiki/Singular_value_decomposition)
- [numpy.linalg.svd](https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html)

Supplementary Reference:
- [The NumPy linear algebra library](https://numpy.org/doc/stable/reference/routines.linalg.html)
- Documents of other meaningful methods of numpy can be found at '[Quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html)' and '[Absolute Beginners Tutorial](https://numpy.org/doc/stable/user/absolute_beginners.html)'

In [3]:
import numpy as np
def singular_value_decomposition(a_matrix):
    u,s,v = np.linalg.svd(a_matrix)
    return s

# you should only complete the above function

def input_a_matrix():
    # nrow = [int(ele) for ele in input().split()][0]
    row_list = []
    while True:
        arow = [int(ele) for ele in input().split()]
        if len(arow) == 0:
            break
        row_list.append(arow)
    
    a_matrix = np.array(row_list)
    return a_matrix
    
image_matrix = input_a_matrix()

output_data = singular_value_decomposition(image_matrix)

row = ["%.3f" % (ele) for ele in output_data]
print(*row, sep=' ')
print()

219 47 68
51 17 120
102 94 160
49 171 190
203 46 205

479.714 181.986 82.291



## 03 Select top k eigenvalues and eigenvectors
### Description
Eigenvalues and eigenvectors can be used for image scaling.

In python we can use '`np.linalg.eig()`' to get eigenvalues and eigenvectors to get them.

Your task is to complete the '`select_topk_eigenvalues_and_eigenvectors`' function, that return the first k (ranking the eigenvalues from greatest to least) eigenvalues and eigenvectors.

![A5_04.png](https://www.sharetechnote.com/image/EngMath_Matrix_EigenDecomposition_02.png)
### Input
The inputs of the '`select_topk_eigenvalues_and_eigenvectors`' function are a '`n*n`' matrix and a number '`k`' (k<=n).
### Output
The outputs of the '`select_topk_eigenvalues_and_eigenvectors`' function are the first k eigenvalues and eigenvectors.

**Sample Input 1**
```
2
10 78 41 44 97 70
78 84 49 44 52 96
41 49 56 71 61 62
44 44 71 88 62 81
97 52 61 62 26 65
70 96 62 81 65 80

# The input includes the above empty line, but not this line
```
**Sample Output 1** 
```
385.883 56.582
0.366 -0.233
0.432 -0.600
0.360 0.368
0.414 0.657
0.381 0.016
0.483 -0.137
```
### Hint
To address this problem, you should
- First, using '[np.linalg.eig](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html)' to get eigenvalues and eigenvectors;
- Secondly, sort the eignvalues and get the indices;
- Finally, slice the top k eigenvalues and eigenvectors according to the indices of sorted eignvalues.

How to get sort an array, i.e. '`w`', and get the indices: `sorted_indices = list(sorted(range(len(w)), key=lambda k: w[k], reverse=True))`.

It is encouraged to try other methods.

Supplement: Documents of other meaningful methods of numpy can be found at '[Quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html)' and '[Absolute Beginners Tutorial](https://numpy.org/doc/stable/user/absolute_beginners.html)'

In [4]:
import numpy as np
def select_topk_eigenvalues_and_eigenvectors(a_matrix, k):
    a = np.linalg.eig(a_matrix)

    a1 = a[0]
    a2 = a[1]


    b = np.argsort(a1)[::-1]
    b1 = a1[b]
    #b2 = a2[b]
    #b3 = [np.take(b2[i],b2[i].s)for i in range(len(a1))]
    #b1 = list(sorted(range(len(a1)), key=lambda k: a1[k], reverse=True))

    for i in range(len(a2)):
        b3 = a2[i]
        #b4 = list(sorted(range(len(b3)), key=lambda k: b3[k], reverse=True))
        b3 = b3[b]
        a2[i] = b3

    b1 = b1[:k]
    a2 = a2[...,:k]

    #print(b1,a2)
    return b1,a2

# you should only complete the above function

def input_a_matrix():
    row_list = []
    while True:
        arow = [float(ele) for ele in input().split()]
        if len(arow) == 0:
            break
        row_list.append(arow)

    a_matrix = np.array(row_list)
    return a_matrix

k = int(input().strip())
image_matrix = input_a_matrix()

output_data = select_topk_eigenvalues_and_eigenvectors(image_matrix, k)

row = ["%.3f" % (ele) for ele in output_data[0]]
print(*row, sep=' ')
for row in output_data[1]:
    row = ["%.3f" % (ele) for ele in row]
    print(*row, sep=' ')
print()

2
10 78 41 44 97 70
78 84 49 44 52 96
41 49 56 71 61 62
44 44 71 88 62 81
97 52 61 62 26 65
70 96 62 81 65 80

385.883 56.582
0.366 -0.233
0.432 -0.600
0.360 0.368
0.414 0.657
0.381 0.016
0.483 -0.137



## 04 Sorting random numbers
### Description
Given two random generated vectors with the same length, i.e. '`A`' and '`B`'. You should complete the '`solution`' function to sort A by descent order and rearrange B according to A’s new index and return the two reordered vectors.

For example, the 'A' is '`[5 1 6]`' and the 'B' is '`[1 2 3]`', then the reordered vectors should be '`[6 5 1]`' and '`[3 1 2]`'.
### Input
The input of the '`solution`' function is two vectors with the same length, i.e.'`A`and`B`'.
### Output
The output of the '`solution`' function is the two reordered vectors.

**Sample Input 1**
```
17 15 14 16 11 13 12 10
26 32 25 31 29 27 28 30
```
**Sample Output 1** 
```
17 16 15 14 13 12 11 10
26 31 32 25 27 28 29 30
```

In [5]:
import numpy as np
def solution(A, B):
    a = np.argsort(A)[::-1]
    a1 = A[a]
    b = B[a]
   
    return a1,b

# you should only complete the above function

def input_two_vectors():
    arow = [int(ele) for ele in input().split()]
    a_vector = np.array(arow)
    arow = [int(ele) for ele in input().split()]
    b_vector = np.array(arow)

    return a_vector, b_vector


A, B = input_two_vectors()

newA, newB = solution(A, B)
print(*newA)
print(*newB)

17 15 14 16 11 13 12 10
26 32 25 31 29 27 28 30
17 16 15 14 13 12 11 10
26 31 32 25 27 28 29 30


## 05 Find max, min and average
### Description
Given a list of integer,find the maximum value and the minimum value and calculate the average value.
### Input
The input is a list of integer.
### Output
The output is themaximum value, the minimum value and the average value.

**Sample Input 1** `1 3 2 4`

**Sample Output 1** `4 1 2.50`

**Sample Input 2** `2 4 2 1 3 6`

**Sample Output 2** `6 1 3.00`
### Hint
You need to use numpy and keep two decimal places for average.

In [6]:
import numpy as np
nums = [int(i) for i in input().split()]
maxn = np.max(nums)
minn = np.min(nums)
argn = np.mean(nums)
end1 = [maxn,minn,'%.2f' % argn]
#np.set_printoptions(precision=3)
print(' '.join('%s' %id for id in end1))

2 4 2 1 3 6
6 1 3.00


## 06 Statistics in real dataset
### Description
In this assignment, you are required to make some basic statistics with the Heart Disease UC dataset, which is popular amongst medical analysis and machine learning. It has 14 columns like age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, thal and target.

Given a segment of that dataset, you should complete the '`solution`' function to return

1. the average value of the 'trestbps' (resting blood pressure) among patients whose age are under 60 (including 60);

2. max value of 'thalach' (heart rate) among female patients (sex column is 1).

### Input
The input of the '`solution`' function is a matrices, i.e. a segment of that dataset.
### Output
The output of the '`solution`' function is a tuple of two values, '`a_mean`, `a_max`'.

**Sample Input 1**
```
50.0 1.0 2.0 129.0 196.0 0.0 1.0 163.0 0.0 0.0 2.0 0.0 2.0 1.0
68.0 0.0 2.0 120.0 211.0 0.0 0.0 115.0 0.0 1.5 1.0 0.0 2.0 1.0
69.0 1.0 3.0 160.0 234.0 1.0 0.0 131.0 0.0 0.1 1.0 1.0 2.0 1.0
45.0 0.0 0.0 138.0 236.0 0.0 0.0 152.0 1.0 0.2 1.0 0.0 2.0 1.0
50.0 0.0 1.0 120.0 244.0 0.0 1.0 162.0 0.0 1.1 2.0 0.0 2.0 1.0
50.0 0.0 0.0 110.0 254.0 0.0 0.0 159.0 0.0 0.0 2.0 0.0 2.0 1.0
64.0 0.0 0.0 180.0 325.0 0.0 1.0 154.0 1.0 0.0 2.0 0.0 2.0 1.0
57.0 1.0 2.0 150.0 126.0 1.0 1.0 173.0 0.0 0.2 2.0 1.0 3.0 1.0
64.0 0.0 2.0 140.0 313.0 0.0 1.0 133.0 0.0 0.2 2.0 0.0 3.0 1.0
43.0 1.0 0.0 110.0 211.0 0.0 1.0 161.0 0.0 0.0 2.0 0.0 3.0 1.0
55.0 1.0 1.0 130.0 262.0 0.0 1.0 155.0 0.0 0.0 2.0 0.0 2.0 1.0
37.0 0.0 2.0 120.0 215.0 0.0 1.0 170.0 0.0 0.0 2.0 0.0 2.0 1.0
41.0 1.0 2.0 130.0 214.0 0.0 0.0 168.0 0.0 2.0 1.0 0.0 2.0 1.0
56.0 1.0 3.0 120.0 193.0 0.0 0.0 162.0 0.0 1.9 1.0 0.0 3.0 1.0
46.0 0.0 1.0 105.0 204.0 0.0 1.0 172.0 0.0 0.0 2.0 0.0 2.0 1.0
46.0 0.0 0.0 138.0 243.0 0.0 0.0 152.0 1.0 0.0 1.0 0.0 2.0 1.0
64.0 0.0 0.0 130.0 303.0 0.0 1.0 122.0 0.0 2.0 1.0 2.0 2.0 1.0
59.0 1.0 0.0 138.0 271.0 0.0 0.0 182.0 0.0 0.0 2.0 0.0 2.0 1.0
41.0 0.0 2.0 112.0 268.0 0.0 0.0 172.0 1.0 0.0 2.0 0.0 2.0 1.0
54.0 0.0 2.0 108.0 267.0 0.0 0.0 167.0 0.0 0.0 2.0 0.0 2.0 1.0
39.0 0.0 2.0 94.0 199.0 0.0 1.0 179.0 0.0 0.0 2.0 0.0 2.0 1.0
34.0 0.0 1.0 118.0 210.0 0.0 1.0 192.0 0.0 0.7 2.0 0.0 2.0 1.0
47.0 1.0 0.0 112.0 204.0 0.0 1.0 143.0 0.0 0.1 2.0 0.0 2.0 1.0
67.0 0.0 2.0 152.0 277.0 0.0 1.0 172.0 0.0 0.0 2.0 1.0 2.0 1.0
52.0 0.0 2.0 136.0 196.0 0.0 0.0 169.0 0.0 0.1 1.0 0.0 2.0 1.0
74.0 0.0 1.0 120.0 269.0 0.0 0.0 121.0 1.0 0.2 2.0 1.0 2.0 1.0
54.0 0.0 2.0 160.0 201.0 0.0 1.0 163.0 0.0 0.0 2.0 1.0 2.0 1.0
49.0 0.0 1.0 134.0 271.0 0.0 1.0 162.0 0.0 0.0 1.0 0.0 2.0 1.0
42.0 1.0 1.0 120.0 295.0 0.0 1.0 162.0 0.0 0.0 2.0 0.0 2.0 1.0
41.0 1.0 1.0 110.0 235.0 0.0 1.0 153.0 0.0 0.0 2.0 0.0 2.0 1.0
41.0 0.0 1.0 126.0 306.0 0.0 1.0 163.0 0.0 0.0 2.0 0.0 2.0 1.0
49.0 0.0 0.0 130.0 269.0 0.0 1.0 163.0 0.0 0.0 2.0 0.0 2.0 1.0
60.0 0.0 2.0 120.0 178.0 1.0 1.0 96.0 0.0 0.0 2.0 0.0 2.0 1.0
62.0 1.0 1.0 128.0 208.0 1.0 0.0 140.0 0.0 0.0 2.0 0.0 2.0 1.0
57.0 1.0 0.0 110.0 201.0 0.0 1.0 126.0 1.0 1.5 1.0 0.0 1.0 1.0
64.0 1.0 0.0 128.0 263.0 0.0 1.0 105.0 1.0 0.2 1.0 1.0 3.0 1.0
51.0 0.0 2.0 120.0 295.0 0.0 0.0 157.0 0.0 0.6 2.0 0.0 2.0 1.0
43.0 1.0 0.0 115.0 303.0 0.0 1.0 181.0 0.0 1.2 1.0 0.0 2.0 1.0
42.0 0.0 2.0 120.0 209.0 0.0 1.0 173.0 0.0 0.0 1.0 0.0 2.0 1.0
67.0 0.0 0.0 106.0 223.0 0.0 1.0 142.0 0.0 0.3 2.0 2.0 2.0 1.0
76.0 0.0 2.0 140.0 197.0 0.0 2.0 116.0 0.0 1.1 1.0 0.0 2.0 1.0
70.0 1.0 1.0 156.0 245.0 0.0 0.0 143.0 0.0 0.0 2.0 0.0 2.0 1.0
44.0 0.0 2.0 118.0 242.0 0.0 1.0 149.0 0.0 0.3 1.0 1.0 2.0 1.0
60.0 0.0 3.0 150.0 240.0 0.0 1.0 171.0 0.0 0.9 2.0 0.0 2.0 1.0
44.0 1.0 2.0 120.0 226.0 0.0 1.0 169.0 0.0 0.0 2.0 0.0 2.0 1.0
42.0 1.0 2.0 130.0 180.0 0.0 1.0 150.0 0.0 0.0 2.0 0.0 2.0 1.0
66.0 1.0 0.0 160.0 228.0 0.0 0.0 138.0 0.0 2.3 2.0 0.0 1.0 1.0
71.0 0.0 0.0 112.0 149.0 0.0 1.0 125.0 0.0 1.6 1.0 0.0 2.0 1.0
64.0 1.0 3.0 170.0 227.0 0.0 0.0 155.0 0.0 0.6 1.0 0.0 3.0 1.0
66.0 0.0 2.0 146.0 278.0 0.0 0.0 152.0 0.0 0.0 1.0 1.0 2.0 1.0
39.0 0.0 2.0 138.0 220.0 0.0 1.0 152.0 0.0 0.0 1.0 0.0 2.0 1.0
58.0 0.0 0.0 130.0 197.0 0.0 1.0 131.0 0.0 0.6 1.0 0.0 2.0 1.0
47.0 1.0 2.0 130.0 253.0 0.0 1.0 179.0 0.0 0.0 2.0 0.0 2.0 1.0
35.0 1.0 1.0 122.0 192.0 0.0 1.0 174.0 0.0 0.0 2.0 0.0 2.0 1.0
58.0 1.0 1.0 125.0 220.0 0.0 1.0 144.0 0.0 0.4 1.0 4.0 3.0 1.0
56.0 1.0 1.0 130.0 221.0 0.0 0.0 163.0 0.0 0.0 2.0 0.0 3.0 1.0
56.0 1.0 1.0 120.0 240.0 0.0 1.0 169.0 0.0 0.0 0.0 0.0 2.0 1.0
55.0 0.0 1.0 132.0 342.0 0.0 1.0 166.0 0.0 1.2 2.0 0.0 2.0 1.0
41.0 1.0 1.0 120.0 157.0 0.0 1.0 182.0 0.0 0.0 2.0 0.0 2.0 1.0
38.0 1.0 2.0 138.0 175.0 0.0 1.0 173.0 0.0 0.0 2.0 4.0 2.0 1.0
38.0 1.0 2.0 138.0 175.0 0.0 1.0 173.0 0.0 0.0 2.0 4.0 2.0 1.0
67.0 1.0 0.0 160.0 286.0 0.0 0.0 108.0 1.0 1.5 1.0 3.0 2.0 0.0
67.0 1.0 0.0 120.0 229.0 0.0 0.0 129.0 1.0 2.6 1.0 2.0 3.0 0.0
62.0 0.0 0.0 140.0 268.0 0.0 0.0 160.0 0.0 3.6 0.0 2.0 2.0 0.0
63.0 1.0 0.0 130.0 254.0 0.0 0.0 147.0 0.0 1.4 1.0 1.0 3.0 0.0
53.0 1.0 0.0 140.0 203.0 1.0 0.0 155.0 1.0 3.1 0.0 0.0 3.0 0.0
56.0 1.0 2.0 130.0 256.0 1.0 0.0 142.0 1.0 0.6 1.0 1.0 1.0 0.0
48.0 1.0 1.0 110.0 229.0 0.0 1.0 168.0 0.0 1.0 0.0 0.0 3.0 0.0
58.0 1.0 1.0 120.0 284.0 0.0 0.0 160.0 0.0 1.8 1.0 0.0 2.0 0.0
58.0 1.0 2.0 132.0 224.0 0.0 0.0 173.0 0.0 3.2 2.0 2.0 3.0 0.0
60.0 1.0 0.0 130.0 206.0 0.0 0.0 132.0 1.0 2.4 1.0 2.0 3.0 0.0
40.0 1.0 0.0 110.0 167.0 0.0 0.0 114.0 1.0 2.0 1.0 0.0 3.0 0.0
60.0 1.0 0.0 117.0 230.0 1.0 1.0 160.0 1.0 1.4 2.0 2.0 3.0 0.0
64.0 1.0 2.0 140.0 335.0 0.0 1.0 158.0 0.0 0.0 2.0 0.0 2.0 0.0
43.0 1.0 0.0 120.0 177.0 0.0 0.0 120.0 1.0 2.5 1.0 0.0 3.0 0.0
57.0 1.0 0.0 150.0 276.0 0.0 0.0 112.0 1.0 0.6 1.0 1.0 1.0 0.0
55.0 1.0 0.0 132.0 353.0 0.0 1.0 132.0 1.0 1.2 1.0 1.0 3.0 0.0
65.0 0.0 0.0 150.0 225.0 0.0 0.0 114.0 0.0 1.0 1.0 3.0 3.0 0.0
61.0 0.0 0.0 130.0 330.0 0.0 0.0 169.0 0.0 0.0 2.0 0.0 2.0 0.0
58.0 1.0 2.0 112.0 230.0 0.0 0.0 165.0 0.0 2.5 1.0 1.0 3.0 0.0
50.0 1.0 0.0 150.0 243.0 0.0 0.0 128.0 0.0 2.6 1.0 0.0 3.0 0.0
44.0 1.0 0.0 112.0 290.0 0.0 0.0 153.0 0.0 0.0 2.0 1.0 2.0 0.0
60.0 1.0 0.0 130.0 253.0 0.0 1.0 144.0 1.0 1.4 2.0 1.0 3.0 0.0
54.0 1.0 0.0 124.0 266.0 0.0 0.0 109.0 1.0 2.2 1.0 1.0 3.0 0.0
50.0 1.0 2.0 140.0 233.0 0.0 1.0 163.0 0.0 0.6 1.0 1.0 3.0 0.0
41.0 1.0 0.0 110.0 172.0 0.0 0.0 158.0 0.0 0.0 2.0 0.0 3.0 0.0
51.0 0.0 0.0 130.0 305.0 0.0 1.0 142.0 1.0 1.2 1.0 0.0 3.0 0.0
58.0 1.0 0.0 128.0 216.0 0.0 0.0 131.0 1.0 2.2 1.0 3.0 3.0 0.0
54.0 1.0 0.0 120.0 188.0 0.0 1.0 113.0 0.0 1.4 1.0 1.0 3.0 0.0
60.0 1.0 0.0 145.0 282.0 0.0 0.0 142.0 1.0 2.8 1.0 2.0 3.0 0.0
60.0 1.0 2.0 140.0 185.0 0.0 0.0 155.0 0.0 3.0 1.0 0.0 2.0 0.0
59.0 1.0 0.0 170.0 326.0 0.0 0.0 140.0 1.0 3.4 0.0 0.0 3.0 0.0
46.0 1.0 2.0 150.0 231.0 0.0 1.0 147.0 0.0 3.6 1.0 0.0 2.0 0.0
67.0 1.0 0.0 125.0 254.0 1.0 1.0 163.0 0.0 0.2 1.0 2.0 3.0 0.0
62.0 1.0 0.0 120.0 267.0 0.0 1.0 99.0 1.0 1.8 1.0 2.0 3.0 0.0
65.0 1.0 0.0 110.0 248.0 0.0 0.0 158.0 0.0 0.6 2.0 2.0 1.0 0.0
44.0 1.0 0.0 110.0 197.0 0.0 0.0 177.0 0.0 0.0 2.0 1.0 2.0 0.0
60.0 1.0 0.0 125.0 258.0 0.0 0.0 141.0 1.0 2.8 1.0 1.0 3.0 0.0
58.0 1.0 0.0 150.0 270.0 0.0 0.0 111.0 1.0 0.8 2.0 0.0 3.0 0.0
68.0 1.0 2.0 180.0 274.0 1.0 0.0 150.0 1.0 1.6 1.0 0.0 3.0 0.0
62.0 0.0 0.0 160.0 164.0 0.0 0.0 145.0 0.0 6.2 0.0 3.0 3.0 0.0
52.0 1.0 0.0 128.0 255.0 0.0 1.0 161.0 1.0 0.0 2.0 1.0 3.0 0.0
59.0 1.0 0.0 110.0 239.0 0.0 0.0 142.0 1.0 1.2 1.0 1.0 3.0 0.0
60.0 0.0 0.0 150.0 258.0 0.0 0.0 157.0 0.0 2.6 1.0 2.0 3.0 0.0
49.0 1.0 2.0 120.0 188.0 0.0 1.0 139.0 0.0 2.0 1.0 3.0 3.0 0.0
59.0 1.0 0.0 140.0 177.0 0.0 1.0 162.0 1.0 0.0 2.0 1.0 3.0 0.0
57.0 1.0 2.0 128.0 229.0 0.0 0.0 150.0 0.0 0.4 1.0 1.0 3.0 0.0
61.0 1.0 0.0 120.0 260.0 0.0 1.0 140.0 1.0 3.6 1.0 1.0 3.0 0.0
39.0 1.0 0.0 118.0 219.0 0.0 1.0 140.0 0.0 1.2 1.0 0.0 3.0 0.0
61.0 0.0 0.0 145.0 307.0 0.0 0.0 146.0 1.0 1.0 1.0 0.0 3.0 0.0
56.0 1.0 0.0 125.0 249.0 1.0 0.0 144.0 1.0 1.2 1.0 1.0 2.0 0.0
43.0 0.0 0.0 132.0 341.0 1.0 0.0 136.0 1.0 3.0 1.0 0.0 3.0 0.0
62.0 0.0 2.0 130.0 263.0 0.0 1.0 97.0 0.0 1.2 1.0 1.0 3.0 0.0
63.0 1.0 0.0 130.0 330.0 1.0 0.0 132.0 1.0 1.8 2.0 3.0 3.0 0.0
65.0 1.0 0.0 135.0 254.0 0.0 0.0 127.0 0.0 2.8 1.0 1.0 3.0 0.0
48.0 1.0 0.0 130.0 256.0 1.0 0.0 150.0 1.0 0.0 2.0 2.0 3.0 0.0
63.0 0.0 0.0 150.0 407.0 0.0 0.0 154.0 0.0 4.0 1.0 3.0 3.0 0.0
55.0 1.0 0.0 140.0 217.0 0.0 1.0 111.0 1.0 5.6 0.0 0.0 3.0 0.0
65.0 1.0 3.0 138.0 282.0 1.0 0.0 174.0 0.0 1.4 1.0 1.0 2.0 0.0
56.0 0.0 0.0 200.0 288.0 1.0 0.0 133.0 1.0 4.0 0.0 2.0 3.0 0.0
54.0 1.0 0.0 110.0 239.0 0.0 1.0 126.0 1.0 2.8 1.0 1.0 3.0 0.0
70.0 1.0 0.0 145.0 174.0 0.0 1.0 125.0 1.0 2.6 0.0 0.0 3.0 0.0

# The input includes the above empty line, but not this line. 
```
**Sample Output 1** `127.814, 182.000`
### Hint
Reference:

- [Filtering Numpy arrays based on conditions](https://www.w3schools.com/python/numpy/numpy_array_filter.asp).

In [7]:
import numpy as np
def solution(a_matrix):
  # columns of a_matrix: 0-age,1-sex,2-cp,3-trestbps,4-chol,5-fbs,6-restecg,7-thalach,8-exang,9-oldpeak,10-slope,11-ca,12-thal,13-target
  #	return a_mean i.e. average value of the ‘trestbps’ (resting blood pressure) among patients whose age are under 60 (including 60).
  #		and a_max i.e. max value of ‘thalach’ (heart rate) among female patients. (sex column is 1)
    a1 = a_matrix
    l = a_matrix.shape[0]
    s = 0
    f = 0
    for i in range(0,l):
        if a1[i-s][0] > 60:
            a1 = np.delete(a1, i-s, axis = 0) # delete whole line
            s = s + 1

    m_mean = a1.mean(axis=0)
  
    a2 = a_matrix
  
    for i in range(0,l):
        if a2[i-f][1] == 0:
            a2 = np.delete(a2, i-f, axis = 0) 
            f = f + 1

    m_max = a2.max(axis=0)
  
    a_mean = m_mean[3]
    a_max = m_max[7]
  
    return (a_mean, a_max)

# You should only complete the above function

def input_a_matrix():
    row_list = []
    while True:
        arow = [float(ele) for ele in input().split()]
        if len(arow) == 0:
            break
        row_list.append(arow)
    
    a_matrix = np.array(row_list)
    return a_matrix

input_data = input_a_matrix()

output_data = solution(input_data)
print("%.3f, %.3f" % output_data)

50.0 1.0 2.0 129.0 196.0 0.0 1.0 163.0 0.0 0.0 2.0 0.0 2.0 1.0
68.0 0.0 2.0 120.0 211.0 0.0 0.0 115.0 0.0 1.5 1.0 0.0 2.0 1.0
69.0 1.0 3.0 160.0 234.0 1.0 0.0 131.0 0.0 0.1 1.0 1.0 2.0 1.0
45.0 0.0 0.0 138.0 236.0 0.0 0.0 152.0 1.0 0.2 1.0 0.0 2.0 1.0
50.0 0.0 1.0 120.0 244.0 0.0 1.0 162.0 0.0 1.1 2.0 0.0 2.0 1.0
50.0 0.0 0.0 110.0 254.0 0.0 0.0 159.0 0.0 0.0 2.0 0.0 2.0 1.0
64.0 0.0 0.0 180.0 325.0 0.0 1.0 154.0 1.0 0.0 2.0 0.0 2.0 1.0
57.0 1.0 2.0 150.0 126.0 1.0 1.0 173.0 0.0 0.2 2.0 1.0 3.0 1.0
64.0 0.0 2.0 140.0 313.0 0.0 1.0 133.0 0.0 0.2 2.0 0.0 3.0 1.0
43.0 1.0 0.0 110.0 211.0 0.0 1.0 161.0 0.0 0.0 2.0 0.0 3.0 1.0
55.0 1.0 1.0 130.0 262.0 0.0 1.0 155.0 0.0 0.0 2.0 0.0 2.0 1.0
37.0 0.0 2.0 120.0 215.0 0.0 1.0 170.0 0.0 0.0 2.0 0.0 2.0 1.0
41.0 1.0 2.0 130.0 214.0 0.0 0.0 168.0 0.0 2.0 1.0 0.0 2.0 1.0
56.0 1.0 3.0 120.0 193.0 0.0 0.0 162.0 0.0 1.9 1.0 0.0 3.0 1.0
46.0 0.0 1.0 105.0 204.0 0.0 1.0 172.0 0.0 0.0 2.0 0.0 2.0 1.0
46.0 0.0 0.0 138.0 243.0 0.0 0.0 152.0 1.0 0.0 1.0 0.0 

## 07 Threshold
### Description
Given a threshold and a list of integers, set all the numbers larger than the threshold to 1, and others to 0.

For example:

Threshold 5, input list [1,2,3,4,5,6,7], the output is [0,0,0,0,0,1,1]

Threshold 3, input list [4,5,1,3,8,5,2], the output is [1,1,0,0,1,1,0]
### Input
The first number of input is the threshold, the rest is a list of integers

For example:

5 1 8 7 9 3 2 6 5  → Threshold 5, input list [1,8,7,9,3,2,6,5]
### Output
The output is a list of 0 and 1.

**Sample Input 1** `5 1 8 7 9 3 2 6 5`

**Sample Output 1** `0 1 1 1 0 0 1 0`

**Sample Input 2** `72 5 8 6 4 1 2`

**Sample Output 2** `0 0 0 0 0 0`
### Hint
Use numpy where to solve this problem with ease.

In [8]:
import numpy as np
nums = input().split()
threshold,nums = int(nums[0]),[int(i) for i in nums[1:]]
nums = np.array(nums)
ends = np.where(nums <= threshold , 0 , 1)
print(' '.join('%s' %id for id in ends))

72 5 8 6 4 1 2
0 0 0 0 0 0
