## Midterm (2022/2023)
### Regulations
1. You are only allowed to use one laptop to answer the questions during the examination;
2. You are not allowed to use any communication software / App during the examination, please turn off or close the background Apps if possible;
3. Except the cases of rule (2), you are free to access any websites you like during the exam;
4. You are allowed to bring any reference books and cheat sheets to the exam venue if you want (subject to the seat space...);
5. You must record the desktop screen during the exam and submit the MD5 in 30 minutes after the examination;
6. In case you finish the examination before 22:00, you are required to complete the MD5 submission before you leave the classroom. The MD5 submission time is a record for verifying your online-judge submissions;
### Mark
- Q1-Q6 (100%)
- Bonus Q7 (5%)

## 01 Chain of diamond
### Description
Given the sizes of each diamond on a chain, your task is to print the diamond chain using the provided function "diamond()"
### Input
Arbitrarily amount of integer separated by comma in one line representing the size of each diamond on the chain.

size<=5
### Output
You should print the diamond chain in column.

**Sample Input 1** `1,2,3`

**Sample Output 1**
```
    *
    *
   ***
    *
    *
   ***
  *****
   ***
    *
```
**Sample Input 2** `5,2,2,2` 

**Sample Output 2**
```
    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *
    *
   ***
    *
    *
   ***
    *
    *
   ***
    *
```
**Sample Input 3** `4,3,3,1,5` 

**Sample Output 3**
```
    *
   ***
  *****
 *******
  *****
   ***
    *
    *
   ***
  *****
   ***
    *
    *
   ***
  *****
   ***
    *
    *
    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *
```
### Hint
You can get the sizes using input(), split() and int()

In [1]:
def diamond(size:int):
    for i in range(size*2-1):
        print(' '*(5-size)+' '*(abs(size-i-1))+'*'*(2* (size-(abs(i+1-size))-1)+1))

sizes = [int(x) for x in input().split(',')]
for i in sizes:
    diamond(i)

4,3,3,1,5
    *
   ***
  *****
 *******
  *****
   ***
    *
    *
   ***
  *****
   ***
    *
    *
   ***
  *****
   ***
    *
    *
    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *


## 02 Sum as a new list
### Description
Use lambda to add two sets of numbers as a new list.

Note:

Use lambda function to solve it. NumPy is not allowed in this question.
### Input
Two sets of numbers（separated by a space）
### Output
A set of numbers（separated by a space）

**Sample Input 1** `3,2,3,4  6,6,0,8`

**Sample Output 1** `9 8 3 12`

**Sample Input 2** `8,2,3,4,4  88,6,7,8,11` 

**Sample Output 2** `96 8 10 12 15`

In [2]:
def SumAsNewList(list1, list2):
    result = map(lambda x,y : x+y,list1, list2 )         
    return result

str1, str2 = input().split()
list1 = list(map(int,str1.split(',')))
list2 = list(map(int,str2.split(',')))

list3 = list(SumAsNewList(list1, list2))
               
for ele in list3:
    print(ele, end=' ')

8,2,3,4,4  88,6,7,8,11
96 8 10 12 15 

## 03 Find the newly inserted letter
### Description
Given two strings `str1` and `str2`, and they only contain lower case letters.

`str2` is randomly generated by shuffling `str1` PLUS inserting a new letter at a random position.

Your task is to find the newly inserted letter in `str2`.

**Note**: The strings (str1 and str2) contain no repeated letter.
### Input
Two strings
### Output
A letter

**Sample Input 1** `qwertyui iuytfrewq`

**Sample Output 1** `f`

**Sample Input 2** `ertyf etyfgr` 

**Sample Output 2** `g`

In [3]:
s, t = input().split()
s=list(s)
t=list(t)
s.sort()
t.sort()
s.append('A')
list1=[]
for i in range(len(t)):
    if s[i] !=t[i]:
        list1.append(t[i])
        break

str1=map(str,list1)
str2=' '.join(str1)
print(str2)

ertyf etyfgr
g


## 04 Make the maximum profit
### Description
Given a list of product prices, you make a profit when you buy a product at lower price at i-th day and then sell it at j-th day(where j>i).

Your task is to find the maximum profit based on the given list of product prices. Return 0 if you cannot achieve any profit.

For example:prices = 2, 1, 3, 2, 7, the maximum profit is 7 - 1 = 6.

Note: you must buy before you sell.
### Input
A set numbers of products' price
### Output
An integer

**Sample Input 1** `7,1,5,3,6,4`

**Sample Output 1** `5`

**Sample Input 2** `11,5,3,1` 

**Sample Output 2** `0`

In [4]:
def maxProfit(prices) -> int:
        cost, profit = float("+inf"), 0
        for price in prices:
            cost = min(cost, price)
            profit = max(profit, price - cost)
        return profit
prices=list(map(int,input().split(",")))
print(maxProfit(prices))

11,5,3,1
0


## 05 License Key Formatting
### Description
You are given a license key represented as a string `s` that consists of only alphanumeric characters and dashes. The string is separated into `n + 1` groups byndashes. You are also given an integer `k`.

We want to reformat the string `s` such that each group contains exactly `k` characters, except for the first group, which could be shorter than `k` but still contains at least one character. Furthermore, there must be a dash in between any two groups.

**You should convert all lowercase letters to uppercase.**
### Input
a string s and an integer k separated by a space
### Output
Print the reformatted license key.

**Sample Input 1** `5F3Z-2e-9-w 4`

**Sample Output 1** `5F3Z-2E9W`

**Sample Input 2** `2-5g-3-J 2` 

**Sample Output 2** `2-5G-3J`
### Hint
- `1 <= s.length <= 105`
- `s` consists of English letters, digits, and dashes`'-'`.
- `1 <= k <= 104`

In [5]:
s,k = input().split(' ',1)
k = int(k)
s = s.replace("-", "").upper()
start = len(s) % k
ans = []
if start != 0:
    ans.append(s[:start])
two = s[start:]
for i in range(len(two) // k):
    ans.append(two[i * k:(i + 1) * k])
re="-".join(ans)
print(re)

2-5g-3-J 2
2-5G-3J


## 06 Use NumPy to process arrays
### Description
NumPy is a Python library used for working with an array. Please use NumPy to complete the following steps:

**Step1. Broadcasting**, the inputs are two sets of numbers (they are separated by a space), they will be treated as a row vector (shape: 1n) and a column vector (shape: n1), your task is to add them and broadcasted to get an array (named arr) (shape: n * n)

**Step2. Column**-wise summation with `arr`, then getting a new array `arr_1`

**Step3. Row**-wise summation with `arr`, then getting a new array `arr_2`

**Step4. Multiply** `arr_1` and `arr_2`, then getting a new array `arr_3`. Finally, please output the result of `arr_3`

Note: You only need to output the result of `arr_3`
### Input
Two sets of numbers (two sets are separated by a space, the numbers in the same set are separated by  ",")
### Output
A set of numbers (separated by a space）

**Sample Input 1** `1,2,3,4  5,6,7,8`

**Sample Output 1** `900 1156 1444 1764`

**Sample Input 2** `7,2,3,41,2  18,9,7,8,10` 

**Sample Output 2** `12615 6200 6030 24415 6510`
### Hint
Step1. Broadcasting, two arrays are considered broadcast compatible if the length of the axis of the trailing dimension (i.e., the dimension from the end) is the same, or the length of one of them is 1.

Add two arrays and broadcasted to get a new matrix:
```
a = [1 2]

b = [[5]
    [6]]
    
a + b =
[[6 7]
[7 8]]
```
Step2:Column-wise summation
```
arr =
[[6 7]
[0 8]]

arr_1 = [6+0 7+8] = [6 15]
```
Step3:Row-wise summation
```
arr =
[[6 7]
[0 8]]

arr_2 = [6+7 0+8] = [13 8]
```
Step4. Multiply two arrays
```
arr_1 =[8 10]

arr_2 = [20 8]

arr_3 = [8 * 20 10 * 8] = [160 80]
```

In [6]:
import numpy as np

def input_a_vector():
    s, t = input().split()
    arr_r = np.array(list(map(int,s.split(','))))
    arr_c = np.array(list(map(int,t.split(','))))
    arr_c = arr_c.reshape((-1, 1))   
    return arr_r, arr_c

arr_r, arr_c = input_a_vector()
  
arr = arr_r+arr_c

# Column-wise summation
arr_1 = np.sum(arr,axis = 0)
  
# Row-wise summation
arr_2 = np.sum(arr,axis = 1)
  
#Multiply 
arr_3 = np.multiply(arr_1,arr_2)

#return your result
for i in arr_3:
    print(i, end=" ")

7,2,3,41,2  18,9,7,8,10
12615 6200 6030 24415 6510 

## 07 (Bonus) Finding the top-k elements from a large list
### Description
Your task is to find the largest `k` elements from a large list of numbers.
### Input
The input contains two parts
1. `k` as problem stated;
2. `nums` represents a numpy array of integers.

### Output
A list of top-kintegers in "**ascending order**".

**Remarks:**

- You can get only 20% marks if you sort the data first and return the top-`k` result.
- Be careful! `k` may be smaller than the size of `nums` (case 2)!!!

**Sample Input 1** `5 1 3 4 5 6`

**Sample Output 1** `1 3 4 5 6`

**Sample Input 2** `10 23123` 

**Sample Output 2** `23123`

**Sample Input 3** `5 1231 3231 3212 3546 6786 751 321 321 32132 14564` 

**Sample Output 3** `3231 3546 6786 14564 32132`
### Hint
Sorting is not preferred because it cause many redundant operation.

In [7]:
import heapq
k,nums = input().split(' ',1)
k = int(k)
nums = [int(x) for x in nums.split()]
max = sorted(heapq.nlargest(k,nums))
print(*max)

5 1231 3231 3212 3546 6786 751 321 321 32132 14564
3231 3546 6786 14564 32132
